[
  { "Collection":"test.test", "Column":"password", "Type": 1, "WhiteUser":"admin" },
  { "Collection":"test.users", "Column":"ssn", "Type": 1, "WhiteUser":"admin" },
  { "Collection":"test.users", "Column":"creditcard", "Type": 2, "WhiteUser":"admin" },
  { "Collection":"test.customers", "Column":"email", "Type": 3, "WhiteUser":"admin" }
]
